// AUTO-GENERATED by scripts/prepare-images.mjs — do not edit

export interface FrogScene {
  condition: string;
  location: string;
  activity: string;
}

export const FROG_SCENES: Record<string, FrogScene[]> = {
  "01": [
    { condition: "sunny", location: "beach", activity: "reading" },
    { condition: "sunny", location: "beach", activity: "sandcastle" },
    { condition: "sunny", location: "beach", activity: "sunscreen" },
    { condition: "sunny", location: "citypark", activity: "picnic" },
    { condition: "sunny", location: "creek", activity: "swimming" },
    { condition: "sunny", location: "field", activity: "biking" },
    { condition: "sunny", location: "field", activity: "hiking" },
    { condition: "sunny", location: "field", activity: "kite" },
    { condition: "sunny", location: "hills", activity: "painting" },
    { condition: "sunny", location: "hills", activity: "reading" },
    { condition: "sunny", location: "hills", activity: "sunbathing" },
    { condition: "sunny", location: "home", activity: "laundry" },
    { condition: "sunny", location: "orchard", activity: "pickingfruit" },
    { condition: "sunny", location: "rooftop", activity: "pinacolada" },
  ],
  "02": [
    { condition: "mostly-sunny", location: "beach", activity: "reading" },
    { condition: "mostly-sunny", location: "beach", activity: "sandcastle" },
    { condition: "mostly-sunny", location: "beach", activity: "sunscreen" },
    { condition: "mostly-sunny", location: "citypark", activity: "picnic" },
    { condition: "mostly-sunny", location: "creek", activity: "swimming" },
    { condition: "mostly-sunny", location: "field", activity: "biking" },
    { condition: "mostly-sunny", location: "field", activity: "hiking" },
    { condition: "mostly-sunny", location: "field", activity: "kite" },
    { condition: "mostly-sunny", location: "hills", activity: "painting" },
    { condition: "mostly-sunny", location: "hills", activity: "reading" },
    { condition: "mostly-sunny", location: "hills", activity: "sunbathing" },
    { condition: "mostly-sunny", location: "home", activity: "laundry" },
    { condition: "mostly-sunny", location: "orchard", activity: "pickingfruit" },
    { condition: "mostly-sunny", location: "rooftop", activity: "pinacolada" },
  ],
  "03": [
    { condition: "partly-cloudy-day", location: "beach", activity: "shells" },
    { condition: "partly-cloudy-day", location: "citypark", activity: "ukelele" },
    { condition: "partly-cloudy-day", location: "creek", activity: "feet" },
    { condition: "partly-cloudy-day", location: "field", activity: "biking" },
    { condition: "partly-cloudy-day", location: "field", activity: "hiking" },
    { condition: "partly-cloudy-day", location: "hills", activity: "painting" },
    { condition: "partly-cloudy-day", location: "hills", activity: "reading" },
    { condition: "partly-cloudy-day", location: "home", activity: "flowers" },
    { condition: "partly-cloudy-day", location: "orchard", activity: "butterflies" },
    { condition: "partly-cloudy-day", location: "orchard", activity: "treeswing" },
  ],
  "04": [
    { condition: "mostly-cloudy-day", location: "beach", activity: "shells" },
    { condition: "mostly-cloudy-day", location: "citypark", activity: "ukelele" },
    { condition: "mostly-cloudy-day", location: "creek", activity: "feet" },
    { condition: "mostly-cloudy-day", location: "field", activity: "biking" },
    { condition: "mostly-cloudy-day", location: "field", activity: "hiking" },
    { condition: "mostly-cloudy-day", location: "hills", activity: "painting" },
    { condition: "mostly-cloudy-day", location: "hills", activity: "reading" },
    { condition: "mostly-cloudy-day", location: "home", activity: "flowers" },
    { condition: "mostly-cloudy-day", location: "orchard", activity: "butterflies" },
    { condition: "mostly-cloudy-day", location: "orchard", activity: "treeswing" },
  ],
  "05": [
    { condition: "clear", location: "creek", activity: "stars" },
    { condition: "clear", location: "field", activity: "lanterns" },
    { condition: "clear", location: "hills", activity: "camping" },
    { condition: "clear", location: "hills", activity: "telescope" },
    { condition: "clear", location: "home", activity: "lounging" },
    { condition: "clear", location: "orchard", activity: "fireflies" },
  ],
  "06": [
    { condition: "mostly-clear", location: "creek", activity: "stars" },
    { condition: "mostly-clear", location: "field", activity: "lanterns" },
    { condition: "mostly-clear", location: "hills", activity: "camping" },
    { condition: "mostly-clear", location: "hills", activity: "telescope" },
    { condition: "mostly-clear", location: "home", activity: "lounging" },
    { condition: "mostly-clear", location: "orchard", activity: "fireflies" },
  ],
  "07": [
    { condition: "partly-cloudy-night", location: "creek", activity: "fireflies" },
    { condition: "partly-cloudy-night", location: "field", activity: "fireflies" },
    { condition: "partly-cloudy-night", location: "hills", activity: "smores" },
    { condition: "partly-cloudy-night", location: "home", activity: "inside" },
    { condition: "partly-cloudy-night", location: "orchard", activity: "eating" },
    { condition: "partly-cloudy-night", location: "rooftop", activity: "dinner" },
  ],
  "08": [
    { condition: "mostly-cloudy-night", location: "creek", activity: "fireflies" },
    { condition: "mostly-cloudy-night", location: "field", activity: "fireflies" },
    { condition: "mostly-cloudy-night", location: "hills", activity: "smores" },
    { condition: "mostly-cloudy-night", location: "home", activity: "inside" },
    { condition: "mostly-cloudy-night", location: "orchard", activity: "eating" },
    { condition: "mostly-cloudy-night", location: "rooftop", activity: "dinner" },
  ],
  "09": [
    { condition: "cloudy", location: "hills", activity: "coffee" },
    { condition: "cloudy", location: "home", activity: "flowers" },
    { condition: "cloudy", location: "orchard", activity: "watching" },
  ],
  "10": [
    { condition: "drizzle", location: "creek", activity: "leaf" },
    { condition: "drizzle", location: "field", activity: "leaf" },
    { condition: "drizzle", location: "hills", activity: "umbrella" },
    { condition: "drizzle", location: "home", activity: "laundry" },
    { condition: "drizzle", location: "orchard", activity: "reading" },
  ],
  "11": [
    { condition: "rain", location: "creek", activity: "leaf" },
    { condition: "rain", location: "field", activity: "leaf" },
    { condition: "rain", location: "hills", activity: "umbrella" },
    { condition: "rain", location: "home", activity: "laundry" },
    { condition: "rain", location: "orchard", activity: "reading" },
  ],
  "12": [
    { condition: "heavy-rain", location: "busstop", activity: "umbrella" },
    { condition: "heavy-rain", location: "creek", activity: "leaf" },
  ],
  "13": [
    { condition: "flurries", location: "citypark", activity: "snowman" },
    { condition: "flurries", location: "creek", activity: "iceskating" },
  ],
  "15": [
    { condition: "snow-showers-snow", location: "citypark", activity: "snowman" },
    { condition: "snow-showers-snow", location: "creek", activity: "skating" },
    { condition: "snow-showers-snow", location: "home", activity: "shoveling" },
  ],
  "16": [
    { condition: "blowing-snow", location: "field", activity: "snowman" },
  ],
  "17": [
    { condition: "heavy-snow-blizzard", location: "creek", activity: "cocoa" },
    { condition: "heavy-snow-blizzard", location: "home", activity: "inside" },
    { condition: "heavy-snow-blizzard", location: "home", activity: "shoveling" },
  ],
  "19": [
    { condition: "mixed-rain-hail-rain-sleet", location: "busstop", activity: "waiting" },
    { condition: "mixed-rain-hail-rain-sleet", location: "cafe", activity: "entering" },
  ],
  "20": [
    { condition: "rain-snow-wintry-mix", location: "citypark", activity: "snowman" },
  ],
  "22": [
    { condition: "iso-thunderstorms", location: "home", activity: "inside" },
  ],
  "24": [
    { condition: "strong-thunderstorms", location: "home", activity: "inside" },
  ],
  "25": [
    { condition: "breezy-windy", location: "creek", activity: "pinwheel" },
    { condition: "breezy-windy", location: "home", activity: "laundry" },
  ],
  "26": [
    { condition: "haze-fog-dust-smoke", location: "field", activity: "lantern" },
  ],
};
