// AUTO-GENERATED by scripts/prepare-images.mjs — do not edit

export interface FrogScene {
  condition: string;
  location: string;
  activity: string;
  layers: ("bg" | "mg" | "fg")[];
}

export const FROG_SCENES: Record<string, FrogScene[]> = {
  "01": [
    { condition: "sunny", location: "beach", activity: "reading", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "beach", activity: "sandcastle", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "beach", activity: "sunscreen", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "citypark", activity: "picnic", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "creek", activity: "swimming", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "field", activity: "biking", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "field", activity: "hiking", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "field", activity: "kite", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "hills", activity: "painting", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "hills", activity: "reading", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "hills", activity: "sunbathing", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "home", activity: "laundry", layers: ["bg", "fg"] },
    { condition: "sunny", location: "orchard", activity: "pickingfruit", layers: ["bg", "mg", "fg"] },
    { condition: "sunny", location: "rooftop", activity: "pinacolada", layers: ["bg", "mg", "fg"] },
  ],
  "02": [
    { condition: "mostly-sunny", location: "beach", activity: "reading", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "beach", activity: "sandcastle", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "beach", activity: "sunscreen", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "citypark", activity: "picnic", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "creek", activity: "swimming", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "field", activity: "biking", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "field", activity: "hiking", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "field", activity: "kite", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "hills", activity: "painting", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "hills", activity: "reading", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "hills", activity: "sunbathing", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "home", activity: "laundry", layers: ["bg", "fg"] },
    { condition: "mostly-sunny", location: "orchard", activity: "pickingfruit", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-sunny", location: "rooftop", activity: "pinacolada", layers: ["bg", "mg", "fg"] },
  ],
  "03": [
    { condition: "partly-cloudy-day", location: "beach", activity: "shells", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-day", location: "citypark", activity: "ukelele", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-day", location: "creek", activity: "feet", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-day", location: "field", activity: "biking", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-day", location: "field", activity: "hiking", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-day", location: "hills", activity: "painting", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-day", location: "hills", activity: "reading", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-day", location: "home", activity: "flowers", layers: ["bg", "fg"] },
    { condition: "partly-cloudy-day", location: "orchard", activity: "butterflies", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-day", location: "orchard", activity: "treeswing", layers: ["bg", "mg", "fg"] },
  ],
  "04": [
    { condition: "mostly-cloudy-day", location: "beach", activity: "shells", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-day", location: "citypark", activity: "ukelele", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-day", location: "creek", activity: "feet", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-day", location: "field", activity: "biking", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-day", location: "field", activity: "hiking", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-day", location: "hills", activity: "painting", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-day", location: "hills", activity: "reading", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-day", location: "home", activity: "flowers", layers: ["bg", "fg"] },
    { condition: "mostly-cloudy-day", location: "orchard", activity: "butterflies", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-day", location: "orchard", activity: "treeswing", layers: ["bg", "mg", "fg"] },
  ],
  "05": [
    { condition: "clear", location: "creek", activity: "stars", layers: ["bg", "mg", "fg"] },
    { condition: "clear", location: "field", activity: "lanterns", layers: ["bg", "mg", "fg"] },
    { condition: "clear", location: "hills", activity: "camping", layers: ["bg", "mg", "fg"] },
    { condition: "clear", location: "hills", activity: "telescope", layers: ["bg", "mg", "fg"] },
    { condition: "clear", location: "home", activity: "lounging", layers: ["bg", "fg"] },
    { condition: "clear", location: "orchard", activity: "fireflies", layers: ["bg", "mg", "fg"] },
  ],
  "06": [
    { condition: "mostly-clear", location: "creek", activity: "stars", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-clear", location: "field", activity: "lanterns", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-clear", location: "hills", activity: "camping", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-clear", location: "hills", activity: "telescope", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-clear", location: "home", activity: "lounging", layers: ["bg", "fg"] },
    { condition: "mostly-clear", location: "orchard", activity: "fireflies", layers: ["bg", "mg", "fg"] },
  ],
  "07": [
    { condition: "partly-cloudy-night", location: "creek", activity: "fireflies", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-night", location: "field", activity: "fireflies", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-night", location: "hills", activity: "smores", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-night", location: "home", activity: "inside", layers: ["bg", "fg"] },
    { condition: "partly-cloudy-night", location: "orchard", activity: "eating", layers: ["bg", "mg", "fg"] },
    { condition: "partly-cloudy-night", location: "rooftop", activity: "dinner", layers: ["bg", "mg", "fg"] },
  ],
  "08": [
    { condition: "mostly-cloudy-night", location: "creek", activity: "fireflies", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-night", location: "field", activity: "fireflies", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-night", location: "hills", activity: "smores", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-night", location: "home", activity: "inside", layers: ["bg", "fg"] },
    { condition: "mostly-cloudy-night", location: "orchard", activity: "eating", layers: ["bg", "mg", "fg"] },
    { condition: "mostly-cloudy-night", location: "rooftop", activity: "dinner", layers: ["bg", "mg", "fg"] },
  ],
  "09": [
    { condition: "cloudy", location: "hills", activity: "coffee", layers: ["bg", "mg", "fg"] },
    { condition: "cloudy", location: "home", activity: "flowers", layers: ["bg", "fg"] },
    { condition: "cloudy", location: "orchard", activity: "watching", layers: ["bg", "mg", "fg"] },
  ],
  "10": [
    { condition: "drizzle", location: "creek", activity: "leaf", layers: ["bg", "mg", "fg"] },
    { condition: "drizzle", location: "field", activity: "leaf", layers: ["bg", "mg", "fg"] },
    { condition: "drizzle", location: "hills", activity: "umbrella", layers: ["bg", "mg", "fg"] },
    { condition: "drizzle", location: "home", activity: "laundry", layers: ["bg", "fg"] },
    { condition: "drizzle", location: "orchard", activity: "reading", layers: ["bg", "mg", "fg"] },
  ],
  "11": [
    { condition: "rain", location: "creek", activity: "leaf", layers: ["bg", "mg", "fg"] },
    { condition: "rain", location: "field", activity: "leaf", layers: ["bg", "mg", "fg"] },
    { condition: "rain", location: "hills", activity: "umbrella", layers: ["bg", "mg", "fg"] },
    { condition: "rain", location: "home", activity: "laundry", layers: ["bg", "fg"] },
    { condition: "rain", location: "orchard", activity: "reading", layers: ["bg", "mg", "fg"] },
  ],
  "12": [
    { condition: "heavy-rain", location: "busstop", activity: "umbrella", layers: ["bg", "mg", "fg"] },
    { condition: "heavy-rain", location: "creek", activity: "leaf", layers: ["bg", "mg", "fg"] },
  ],
  "13": [
    { condition: "flurries", location: "citypark", activity: "snowman", layers: ["bg", "mg", "fg"] },
    { condition: "flurries", location: "creek", activity: "iceskating", layers: ["bg", "mg", "fg"] },
  ],
  "15": [
    { condition: "snow-showers-snow", location: "citypark", activity: "snowman", layers: ["bg", "mg", "fg"] },
    { condition: "snow-showers-snow", location: "creek", activity: "skating", layers: ["bg", "mg", "fg"] },
    { condition: "snow-showers-snow", location: "home", activity: "shoveling", layers: ["bg", "fg"] },
  ],
  "16": [
    { condition: "blowing-snow", location: "field", activity: "snowman", layers: ["bg", "mg", "fg"] },
  ],
  "17": [
    { condition: "heavy-snow-blizzard", location: "creek", activity: "cocoa", layers: ["bg", "mg", "fg"] },
    { condition: "heavy-snow-blizzard", location: "home", activity: "inside", layers: ["bg", "fg"] },
    { condition: "heavy-snow-blizzard", location: "home", activity: "shoveling", layers: ["bg", "fg"] },
  ],
  "19": [
    { condition: "mixed-rain-hail-rain-sleet", location: "busstop", activity: "waiting", layers: ["bg", "mg", "fg"] },
    { condition: "mixed-rain-hail-rain-sleet", location: "cafe", activity: "entering", layers: ["bg", "mg", "fg"] },
  ],
  "20": [
    { condition: "rain-snow-wintry-mix", location: "citypark", activity: "snowman", layers: ["bg", "mg", "fg"] },
  ],
  "22": [
    { condition: "iso-thunderstorms", location: "home", activity: "inside", layers: ["bg", "fg"] },
  ],
  "24": [
    { condition: "strong-thunderstorms", location: "home", activity: "inside", layers: ["bg", "fg"] },
  ],
  "25": [
    { condition: "breezy-windy", location: "creek", activity: "pinwheel", layers: ["bg", "mg", "fg"] },
    { condition: "breezy-windy", location: "home", activity: "laundry", layers: ["bg", "fg"] },
  ],
  "26": [
    { condition: "haze-fog-dust-smoke", location: "field", activity: "lantern", layers: ["bg", "mg", "fg"] },
  ],
};
