import { readdir, mkdir, copyFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";

const SRC_DIR = "frog-images-optimized/square";
const OUT_DIR = "public/frog";
const CATALOG_PATH = "lib/frog-scenes.ts";

// Known locations in the frog image filenames.
// Used to split the variable-length condition from location-activity.
const KNOWN_LOCATIONS = [
  "beach", "busstop", "cafe", "citypark", "creek",
  "field", "hills", "home", "orchard", "rooftop",
];

function parseFilename(filename) {
  // Pattern: {code}-{condition...}-{location}-{activity}_{layer}.png
  // e.g. "03-partly-cloudy-day-beach-shells_bg.png"
  const base = filename.replace(/\.png$/, "");
  const layerMatch = base.match(/_(bg|mg|fg)$/);
  if (!layerMatch) return null;

  const layer = layerMatch[1];
  const prefix = base.slice(0, -layer.length - 1); // remove _bg/_mg/_fg

  // Extract code (first segment before first hyphen, always 2 digits)
  const firstHyphen = prefix.indexOf("-");
  if (firstHyphen === -1) return null;
  const code = prefix.slice(0, firstHyphen);

  // Find the location by searching for known locations in the remaining string
  const rest = prefix.slice(firstHyphen + 1); // everything after "01-"
  const parts = rest.split("-");

  let locationIdx = -1;
  for (let i = 0; i < parts.length; i++) {
    if (KNOWN_LOCATIONS.includes(parts[i])) {
      locationIdx = i;
      break;
    }
  }
  if (locationIdx === -1) return null;

  const condition = parts.slice(0, locationIdx).join("-");
  const location = parts[locationIdx];
  const activity = parts.slice(locationIdx + 1).join("-");

  return { code, condition, location, activity, layer, prefix };
}

async function main() {
  // Ensure output directory exists
  await mkdir(OUT_DIR, { recursive: true });

  const files = (await readdir(SRC_DIR)).filter((f) => f.endsWith(".png"));
  console.log(`Found ${files.length} images in ${SRC_DIR}`);

  // Copy all files
  let copied = 0;
  for (const file of files) {
    await copyFile(join(SRC_DIR, file), join(OUT_DIR, file));
    copied++;
  }
  console.log(`Copied ${copied} files to ${OUT_DIR}`);

  // Build scene catalog (only from _bg files to avoid triple-counting)
  const scenes = new Map(); // code -> Set of "condition|location|activity"
  for (const file of files) {
    const parsed = parseFilename(file);
    if (!parsed || parsed.layer !== "bg") continue;

    const key = parsed.code;
    if (!scenes.has(key)) scenes.set(key, new Set());
    scenes.get(key).add(`${parsed.condition}|${parsed.location}|${parsed.activity}`);
  }

  // Generate TypeScript catalog
  const lines = [
    "// AUTO-GENERATED by scripts/prepare-images.mjs — do not edit",
    "",
    "export interface FrogScene {",
    "  condition: string;",
    "  location: string;",
    "  activity: string;",
    "}",
    "",
    "export const FROG_SCENES: Record<string, FrogScene[]> = {",
  ];

  const sortedCodes = [...scenes.keys()].sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  for (const code of sortedCodes) {
    const sceneList = [...scenes.get(code)].sort();
    lines.push(`  "${code}": [`);
    for (const scene of sceneList) {
      const [condition, location, activity] = scene.split("|");
      lines.push(`    { condition: "${condition}", location: "${location}", activity: "${activity}" },`);
    }
    lines.push("  ],");
  }

  lines.push("};");
  lines.push("");

  await mkdir(dirname(CATALOG_PATH), { recursive: true });
  await writeFile(CATALOG_PATH, lines.join("\n"));
  console.log(`Generated ${CATALOG_PATH} with ${sortedCodes.length} codes`);
}

main();
